global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:

  # Scrape the backend service itself (basic metrics, if any)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']

  # Scrape node_exporter (server CPU, RAM, Disk metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Probe the backend /health endpoint using blackbox_exporter
  - job_name: 'blackbox-probe-backend-health'
    metrics_path: /probe
    params:
      module: [http_2xx]

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']

    static_configs:
      - targets:
          - http://backend:3000/health

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

