name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run tests
      run: |
        cd frontend
        npm test
    
    - name: Build
      run: |
        cd frontend
        npm run build
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        cd frontend
        npm run deploy

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          tags: peymansohi/simple-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          tags: peymansohi- name: Checkout repository
  uses: actions/checkout@v4

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v3

- name: Login to DockerHub
  uses: docker/login-action@v3
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Build and push backend image
  uses: docker/build-push-action@v5
  with:
    context: ./backend
    push: true
    tags: peymansohi/simple-backend:latest

- name: Build and push frontend image
  uses: docker/build-push-action@v5
  with:
    context: ./frontend
    push: true
    tags: peymansohi/simple-frontend:latest

- name: Save logs
  run: |
    mkdir -p logs
    cp -r ./backend/logs ./logs/backend
    cp -r ./frontend/logs ./logs/frontend
    tar -czf logs.tar.gz logs

- name: Upload logs
  uses: actions/upload-artifact@v3
  with:
    name: logs
    path: logs.tar.gz- name: Save logs
  run: |
    mkdir -p logs
    cp -r ./backend/logs ./logs/backend
    cp -r ./frontend/logs ./logs/frontend
    tar -czf logs.tar.gz logs

- name: Upload logs
  uses: actions/upload-artifact@v3
  with:
    name: logs
    path: logs.tar.gz/simple-frontend:latest

