apiVersion: v2
name: micromon
description: A Helm chart for Micromon application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Your Name
    email: your.email@example.com 